server:
  port: 81


eureka:
  client:
    # 表示将自己注入EurekaService，默认为true
    register-with-eureka: true
    # 是否从 Eureka Service 抓取已有的信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka  # 单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka    # 集群版
  instance:
    instance-id: consumer80
    prefer-ip-address: true       # 显示 EurekaService 服务注册中心的每个Client的 ip 地址信息

spring:
  application:
    name: cloud-order-service